

ALTER SEQUENCE BANCO_ID_SEQ RESTART WITH 162;
ALTER SEQUENCE CONTA_CAIXA_ID_SEQ RESTART WITH 2;
ALTER SEQUENCE FIN_DOCUMENTO_ORIGEM_ID_SEQ RESTART WITH 101;
ALTER SEQUENCE plano_centro_resultado_id_seq RESTART WITH 5;
ALTER SEQUENCE centro_resultado_id_seq RESTART WITH 16;
ALTER SEQUENCE plano_natureza_financeira_id_seq RESTART WITH 5;
ALTER SEQUENCE natureza_financeira_id_seq RESTART WITH 67;

ALTER SEQUENCE PAIS_ID_SEQ RESTART WITH 239;
ALTER SEQUENCE UF_ID_SEQ RESTART WITH 28;
ALTER SEQUENCE MUNICIPIO_ID_SEQ RESTART WITH 5392;
ALTER SEQUENCE NCM_ID_SEQ RESTART WITH 11565;


ALTER SEQUENCE EFD_TABELA_437_ID_SEQ RESTART WITH 19;
ALTER SEQUENCE CFOP_ID_SEQ RESTART WITH 542;
ALTER SEQUENCE CNAE_ID_SEQ RESTART WITH 1300;
ALTER SEQUENCE CST_ICMS_A_ID_SEQ RESTART WITH 4;
ALTER SEQUENCE CST_ICMS_B_ID_SEQ RESTART WITH 12;
ALTER SEQUENCE CSOSN_A_ID_SEQ RESTART WITH 4;
ALTER SEQUENCE CSOSN_B_ID_SEQ RESTART WITH 11;
ALTER SEQUENCE CST_COFINS_ID_SEQ RESTART WITH 34;
ALTER SEQUENCE CST_IPI_ID_SEQ RESTART WITH 16;
ALTER SEQUENCE CST_PIS_ID_SEQ RESTART WITH 35;
ALTER SEQUENCE EFD_TABELA_4310_ID_SEQ RESTART WITH 31;
ALTER SEQUENCE EFD_TABELA_4313_ID_SEQ RESTART WITH 78;
ALTER SEQUENCE EFD_TABELA_4314_ID_SEQ RESTART WITH 19;
ALTER SEQUENCE EFD_TABELA_4315_ID_SEQ RESTART WITH 15;
ALTER SEQUENCE EFD_TABELA_4316_ID_SEQ RESTART WITH 136;
ALTER SEQUENCE EFD_TABELA_439_ID_SEQ RESTART WITH 12;

ALTER SEQUENCE TIPO_ADMISSAO_ID_SEQ RESTART WITH 6;
ALTER SEQUENCE TIPO_ITEM_SPED_ID_SEQ RESTART WITH 13;
ALTER SEQUENCE TIPO_RELACIONAMENTO_ID_SEQ RESTART WITH 9;
ALTER SEQUENCE CARGO_ID_SEQ RESTART WITH 2;
ALTER SEQUENCE SETOR_ID_SEQ RESTART WITH 2;
ALTER SEQUENCE NIVEL_FORMACAO_ID_SEQ RESTART WITH 14;
ALTER SEQUENCE TIPO_COLABORADOR_ID_SEQ RESTART WITH 3;
ALTER SEQUENCE SITUACAO_COLABORADOR_ID_SEQ RESTART WITH 3;
ALTER SEQUENCE ESTADO_CIVIL_ID_SEQ RESTART WITH 6;
ALTER SEQUENCE colaborador_id_seq RESTART WITH 2;

ALTER SEQUENCE PAPEL_ID_SEQ RESTART WITH 3;
ALTER SEQUENCE USUARIO_ID_SEQ RESTART WITH 2;
ALTER SEQUENCE NOTA_FISCAL_MODELO_ID_SEQ RESTART WITH 33;

ALTER SEQUENCE produto_grupo_id_seq RESTART WITH 10;
ALTER SEQUENCE UNIDADE_PRODUTO_ID_SEQ RESTART WITH 23;

ALTER SEQUENCE empresa_id_seq RESTART WITH 2;
ALTER SEQUENCE empresa_endereco_id_seq RESTART WITH 2;
ALTER SEQUENCE empresa_contato_id_seq RESTART WITH 2;
ALTER SEQUENCE empresa_telefone_id_seq RESTART WITH 2;

ALTER SEQUENCE pessoa_id_seq RESTART WITH 2;
ALTER SEQUENCE pessoa_endereco_id_seq RESTART WITH 2;
ALTER SEQUENCE PESSOA_JURIDICA_id_seq RESTART WITH 2;
ALTER SEQUENCE empresa_pessoa_id_seq RESTART WITH 2;
ALTER SEQUENCE situacao_for_cli_id_seq RESTART WITH 3;
ALTER SEQUENCE ATIVIDADE_FOR_CLI_ID_SEQ RESTART WITH 2;

ALTER SEQUENCE tribut_operacao_fiscal_id_seq RESTART WITH 9;
ALTER SEQUENCE tribut_grupo_tributario_id_seq RESTART WITH 5;

ALTER SEQUENCE venda_condicoes_pagamento_id_seq RESTART WITH 12;
ALTER SEQUENCE venda_condicoes_parcelas_id_seq RESTART WITH 56;


