/*
  EMPRESA
  -------
*/
INSERT INTO EMPRESA (ID, RAZAO_SOCIAL, NOME_FANTASIA, CNPJ, INSCRICAO_ESTADUAL,  INSCRICAO_MUNICIPAL, TIPO, DATA_CADASTRO,  EMAIL, CODIGO_IBGE_CIDADE, CODIGO_IBGE_UF,TIPO_CONTROLE_ESTOQUE)
VALUES (1, '${razaoSocial}', '${fantasia}', '${cnpj}', '${inscricaoEstadual}',  '${inscricaoMunicipal}', 'M',now(),'${email}', '${codigoIbgeCidade}', '${codigoIbgeUf}','D');


/*
  EMPRESA_ENDERECO
  -------
*/
insert into EMPRESA_ENDERECO (ID, ID_EMPRESA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, CEP, MUNICIPIO_IBGE, UF, PRINCIPAL, ENTREGA, COBRANCA, CORRESPONDENCIA)
values(1,1,'${logradouro}','${numero}','${complemento}','${bairro}','${cidade}','${cep}','${codigoIbgeCidade}','${codigoIbgeUf}','S','S','S','S');

/*
  EMPRESA_TELEFONE
  -------
*/
insert into EMPRESA_TELEFONE (ID, ID_EMPRESA, TIPO, NUMERO) values(1,1,0,'${fone}');


/*
  PESSOA
*/
insert into PESSOA (ID, NOME, TIPO, EMAIL, SITE, CLIENTE, FORNECEDOR, COLABORADOR, TRANSPORTADORA) values('1','CLIENTE PADRAO','F','pf@gmail.com',NULL,'S','N','N','N');
insert into PESSOA (ID, NOME, TIPO, EMAIL, SITE, CLIENTE, FORNECEDOR, COLABORADOR, TRANSPORTADORA) values('2','${fantasia}','J','pj@gmail.com',NULL,'N','N','S','N');

/*
  PESSOA_ENDERECO
  -------
*/
insert into PESSOA_ENDERECO (ID, ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, CEP, MUNICIPIO_IBGE, UF, PRINCIPAL, ENTREGA, COBRANCA, CORRESPONDENCIA) values('1','1','LOGRADOURO CLIENTE PADRAO','2','COMPLEMENTO','BAIRRO','CIDADE','71000000','5300108','DF','S',NULL,NULL,NULL);
insert into PESSOA_ENDERECO (ID, ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, CEP, MUNICIPIO_IBGE, UF, PRINCIPAL, ENTREGA, COBRANCA, CORRESPONDENCIA) values('2','2','LOGRADOURO USUARIO PADRAO','3','COMPLEMENTO','BAIRRO','CIDADE','72000000','5300108','DF','S',NULL,NULL,NULL);



/*
  EMPRESA_PESSOA
  -------
*/

INSERT INTO EMPRESA_PESSOA(ID,ID_EMPRESA,ID_PESSOA,RESPONSAVEL_LEGAL) values (1,1,1,'N');
INSERT INTO EMPRESA_PESSOA(ID,ID_EMPRESA,ID_PESSOA,RESPONSAVEL_LEGAL) values (2,1,2,'N');

/*
  PESSOA_FISICA
  -------------
*/
insert into PESSOA_FISICA (ID, ID_PESSOA, ID_ESTADO_CIVIL, CPF, RG, ORGAO_RG, DATA_EMISSAO_RG, DATA_NASCIMENTO, SEXO, NATURALIDADE, NACIONALIDADE, RACA, TIPO_SANGUE, CNH_NUMERO, CNH_CATEGORIA, CNH_VENCIMENTO, TITULO_ELEITORAL_NUMERO, TITULO_ELEITORAL_ZONA, TITULO_ELEITORAL_SECAO, RESERVISTA_NUMERO, RESERVISTA_CATEGORIA, NOME_MAE, NOME_PAI) values('1','1','1','11111111111','123456','SSP-SP','1980-01-01','1970-01-01','M','BRASILIA','BRASILEIRA','B',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'MARIA JOSE','JOSE MARIA');
insert into PESSOA_FISICA (ID, ID_PESSOA, ID_ESTADO_CIVIL, CPF, RG, ORGAO_RG, DATA_EMISSAO_RG, DATA_NASCIMENTO, SEXO, NATURALIDADE, NACIONALIDADE, RACA, TIPO_SANGUE, CNH_NUMERO, CNH_CATEGORIA, CNH_VENCIMENTO, TITULO_ELEITORAL_NUMERO, TITULO_ELEITORAL_ZONA, TITULO_ELEITORAL_SECAO, RESERVISTA_NUMERO, RESERVISTA_CATEGORIA, NOME_MAE, NOME_PAI) values('2','2','1','22222222222','123456','SSP-SP','1980-01-01','1970-01-01','M','BRASILIA','BRASILEIRA','B',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'MARIA JOSE','JOSE MARIA');


/*
  CLIENTE
  -------
*/
INSERT INTO CLIENTE (ID, ID_PESSOA, ID_ATIVIDADE_FOR_CLI, ID_SITUACAO_FOR_CLI) VALUES (1, 1, 1, 1);

/*
  SETOR
  -----
*/
INSERT INTO SETOR (ID, ID_EMPRESA, NOME, DESCRICAO) VALUES (1, 1, 'ADMINISTRACAO', NULL);


/*
  CARGO
*/
INSERT INTO CARGO (ID, ID_EMPRESA, NOME, DESCRICAO, SALARIO, CBO_1994, CBO_2002) VALUES (1, 1, 'ADMINISTRADOR', NULL, 5000, NULL, '252105');

/*
  COLABORADOR
*/
INSERT INTO COLABORADOR (ID, ID_PESSOA, ID_NIVEL_FORMACAO, ID_CARGO, ID_SETOR, ID_TIPO_COLABORADOR, ID_SITUACAO_COLABORADOR) VALUES (1, 2, 1, 1, 1, 1, 1);


/*
  USUARIO
  -------
*/
INSERT INTO USUARIO (ID, ID_COLABORADOR, ID_PAPEL, LOGIN, SENHA, DATA_CADASTRO, ADMINISTRADOR) VALUES (1, 1, 1, '${email}', '${senha}',now(), 'S');

