CREATE TABLE FIN_LANCAMENTO_RECEBER_CARTAO (
  ID                       SERIAL  NOT NULL,
  ID_OPERADORA_CARTAO      INTEGER NOT NULL,
  ID_EMPRESA               INTEGER NOT NULL,
  QUANTIDADE_PARCELA       INTEGER,
  VALOR_BRUTO              DECIMAL(18, 6),
  TAXA_APLICADA            DECIMAL(18, 6),
  VALOR_ENCARGOS           DECIMAL(18, 6),
  VALOR_LIQUIDO            DECIMAL(18, 6),
  DATA_LANCAMENTO          DATE,
  PRIMEIRO_VENCIMENTO      DATE,
  INTERVALO_ENTRE_PARCELAS INTEGER,
  NUMERO_DOCUMENTO         VARCHAR(50),
  CODIGO_MODULO_LCTO       CHAR(3),
  HASH_MODULO_LCTO         VARCHAR(32),
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_OPERADORA_CARTAO) REFERENCES OPERADORA_CARTAO (ID),
  FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID)
);

CREATE TABLE FIN_PARCELA_RECEBER_CARTAO (
  ID                               SERIAL  NOT NULL,
  ID_FIN_LANCAMENTO_RECEBER_CARTAO INTEGER NOT NULL,
  ID_CONTA_CAIXA                   INTEGER NOT NULL,
  NUMERO_PARCELA                   INTEGER,
  DATA_EMISSAO                     DATE,
  DATA_VENCIMENTO                  DATE,
  DATA_RECEBIMENTO                 DATE,
  VALOR_BRUTO                      DECIMAL(18, 6),
  TAXA_APLICADA                    DECIMAL(18, 6),
  VALOR_ENCARGOS                   DECIMAL(18, 6),
  VALOR_LIQUIDO                    DECIMAL(18, 6),
  PAGO                             BOOLEAN,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_FIN_LANCAMENTO_RECEBER_CARTAO) REFERENCES FIN_LANCAMENTO_RECEBER_CARTAO (ID),
  FOREIGN KEY (ID_CONTA_CAIXA) REFERENCES CONTA_CAIXA (ID)
);

