SELECT setval('municipio_id_seq', (select COALESCE((SELECT (MAX(id) + 1) from MUNICIPIO), 1)), false);

INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4100103', 'Abatiá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4100202', 'Adrianópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4100301', 'Agudos do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4100400', 'Almirante Tamandaré', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4100459', 'Altamira do Paraná', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4100509', 'Altônia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4100608', 'Alto Paraná', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4100707', 'Alto Piquiri', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4100806', 'Alvorada do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4100905', 'Amaporã', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101002', 'Ampére', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101051', 'Anahy', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101101', 'Andirá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101150', 'Ângulo', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101200', 'Antonina', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101309', 'Antônio Olinto', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101408', 'Apucarana', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101507', 'Arapongas', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101606', 'Arapoti', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101655', 'Arapuã', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101705', 'Araruna', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101804', 'Araucária', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101853', 'Ariranha do Ivaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4101903', 'Assaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4102000', 'Assis Chateaubriand', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4102109', 'Astorga', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4102208', 'Atalaia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4102307', 'Balsa Nova', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4102406', 'Bandeirantes', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4102505', 'Barbosa Ferraz', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4102604', 'Barracão', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4102703', 'Barra do Jacaré', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4102752', 'Bela Vista da Caroba', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4102802', 'Bela Vista do Paraíso', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4102901', 'Bituruna', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103008', 'Boa Esperança', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103024', 'Boa Esperança do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103040', 'Boa Ventura de São Roque', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103057', 'Boa Vista da Aparecida', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103107', 'Bocaiúva do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103156', 'Bom Jesus do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103206', 'Bom Sucesso', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103222', 'Bom Sucesso do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103305', 'Borrazópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103354', 'Braganey', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103370', 'Brasilândia do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103404', 'Cafeara', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103453', 'Cafelândia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103479', 'Cafezal do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103503', 'Califórnia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103602', 'Cambará', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103701', 'Cambé', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103800', 'Cambira', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103909', 'Campina da Lagoa', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4103958', 'Campina do Simão', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104006', 'Campina Grande do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104055', 'Campo Bonito', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104105', 'Campo do Tenente', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104204', 'Campo Largo', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104253', 'Campo Magro', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104303', 'Campo Mourão', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104402', 'Cândido de Abreu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104428', 'Candói', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104451', 'Cantagalo', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104501', 'Capanema', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104600', 'Capitão Leônidas Marques', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104659', 'Carambeí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104709', 'Carlópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104808', 'Cascavel', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4104907', 'Castro', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4105003', 'Catanduvas', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4105102', 'Centenário do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4105201', 'Cerro Azul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4105300', 'Céu Azul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4105409', 'Chopinzinho', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4105508', 'Cianorte', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4105607', 'Cidade Gaúcha', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4105706', 'Clevelândia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4105805', 'Colombo', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4105904', 'Colorado', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106001', 'Congonhinhas', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106100', 'Conselheiro Mairinck', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106209', 'Contenda', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106308', 'Corbélia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106407', 'Cornélio Procópio', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106456', 'Coronel Domingos Soares', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106506', 'Coronel Vivida', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106555', 'Corumbataí do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106571', 'Cruzeiro do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106605', 'Cruzeiro do Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106704', 'Cruzeiro do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106803', 'Cruz Machado', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106852', 'Cruzmaltina', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4106902', 'Curitiba', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107009', 'Curiúva', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107108', 'Diamante do Norte', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107124', 'Diamante do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107157', 'Diamante D''Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107207', 'Dois Vizinhos', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107256', 'Douradina', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107306', 'Doutor Camargo', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107405', 'Enéas Marques', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107504', 'Engenheiro Beltrão', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107520', 'Esperança Nova', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107538', 'Entre Rios do Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107546', 'Espigão Alto do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107553', 'Farol', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107603', 'Faxinal', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107652', 'Fazenda Rio Grande', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107702', 'Fênix', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107736', 'Fernandes Pinheiro', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107751', 'Figueira', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107801', 'Floraí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107850', 'Flor da Serra do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4107900', 'Floresta', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108007', 'Florestópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108106', 'Flórida', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108205', 'Formosa do Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108304', 'Foz do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108320', 'Francisco Alves', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108403', 'Francisco Beltrão', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108452', 'Foz do Jordão', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108502', 'General Carneiro', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108551', 'Godoy Moreira', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108601', 'Goioerê', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108650', 'Goioxim', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108700', 'Grandes Rios', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108809', 'Guaíra', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108908', 'Guairaçá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4108957', 'Guamiranga', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109005', 'Guapirama', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109104', 'Guaporema', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109203', 'Guaraci', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109302', 'Guaraniaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109401', 'Guarapuava', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109500', 'Guaraqueçaba', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109609', 'Guaratuba', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109658', 'Honório Serpa', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109708', 'Ibaiti', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109757', 'Ibema', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109807', 'Ibiporã', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4109906', 'Icaraíma', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110003', 'Iguaraçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110052', 'Iguatu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110078', 'Imbaú', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110102', 'Imbituva', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110201', 'Inácio Martins', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110300', 'Inajá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110409', 'Indianópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110508', 'Ipiranga', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110607', 'Iporã', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110656', 'Iracema do Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110706', 'Irati', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110805', 'Iretama', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110904', 'Itaguajé', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4110953', 'Itaipulândia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111001', 'Itambaracá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111100', 'Itambé', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111209', 'Itapejara D''Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111258', 'Itaperuçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111308', 'Itaúna do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111407', 'Ivaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111506', 'Ivaiporã', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111555', 'Ivaté', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111605', 'Ivatuba', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111704', 'Jaboti', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111803', 'Jacarezinho', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4111902', 'Jaguapitã', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112009', 'Jaguariaíva', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112108', 'Jandaia do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112207', 'Janiópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112306', 'Japira', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112405', 'Japurá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112504', 'Jardim Alegre', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112603', 'Jardim Olinda', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112702', 'Jataizinho', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112751', 'Jesuítas', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112801', 'Joaquim Távora', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112900', 'Jundiaí do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4112959', 'Juranda', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113007', 'Jussara', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113106', 'Kaloré', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113205', 'Lapa', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113254', 'Laranjal', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113304', 'Laranjeiras do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113403', 'Leópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113429', 'Lidianópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113452', 'Lindoeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113502', 'Loanda', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113601', 'Lobato', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113700', 'Londrina', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113734', 'Luiziana', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113759', 'Lunardelli', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113809', 'Lupionópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4113908', 'Mallet', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4114005', 'Mamborê', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4114104', 'Mandaguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4114203', 'Mandaguari', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4114302', 'Mandirituba', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4114351', 'Manfrinópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4114401', 'Mangueirinha', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4114500', 'Manoel Ribas', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4114609', 'Marechal Cândido Rondon', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4114708', 'Maria Helena', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4114807', 'Marialva', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4114906', 'Marilândia do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115002', 'Marilena', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115101', 'Mariluz', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115200', 'Maringá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115309', 'Mariópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115358', 'Maripá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115408', 'Marmeleiro', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115457', 'Marquinho', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115507', 'Marumbi', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115606', 'Matelândia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115705', 'Matinhos', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115739', 'Mato Rico', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115754', 'Mauá da Serra', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115804', 'Medianeira', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115853', 'Mercedes', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4115903', 'Mirador', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116000', 'Miraselva', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116059', 'Missal', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116109', 'Moreira Sales', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116208', 'Morretes', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116307', 'Munhoz de Melo', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116406', 'Nossa Senhora das Graças', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116505', 'Nova Aliança do Ivaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116604', 'Nova América da Colina', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116703', 'Nova Aurora', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116802', 'Nova Cantu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116901', 'Nova Esperança', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4116950', 'Nova Esperança do Sudoeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117008', 'Nova Fátima', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117057', 'Nova Laranjeiras', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117107', 'Nova Londrina', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117206', 'Nova Olímpia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117214', 'Nova Santa Bárbara', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117222', 'Nova Santa Rosa', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117255', 'Nova Prata do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117271', 'Nova Tebas', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117297', 'Novo Itacolomi', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117305', 'Ortigueira', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117404', 'Ourizona', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117453', 'Ouro Verde do Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117503', 'Paiçandu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117602', 'Palmas', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117701', 'Palmeira', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117800', 'Palmital', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4117909', 'Palotina', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118006', 'Paraíso do Norte', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118105', 'Paranacity', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118204', 'Paranaguá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118303', 'Paranapoema', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118402', 'Paranavaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118451', 'Pato Bragado', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118501', 'Pato Branco', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118600', 'Paula Freitas', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118709', 'Paulo Frontin', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118808', 'Peabiru', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118857', 'Perobal', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4118907', 'Pérola', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119004', 'Pérola D''Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119103', 'Piên', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119152', 'Pinhais', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119202', 'Pinhalão', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119251', 'Pinhal de São Bento', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119301', 'Pinhão', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119400', 'Piraí do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119509', 'Piraquara', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119608', 'Pitanga', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119657', 'Pitangueiras', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119707', 'Planaltina do Paraná', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119806', 'Planalto', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119905', 'Ponta Grossa', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4119954', 'Pontal do Paraná', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120002', 'Porecatu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120101', 'Porto Amazonas', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120150', 'Porto Barreiro', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120200', 'Porto Rico', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120309', 'Porto Vitória', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120333', 'Prado Ferreira', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120358', 'Pranchita', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120408', 'Presidente Castelo Branco', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120507', 'Primeiro de Maio', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120606', 'Prudentópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120655', 'Quarto Centenário', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120705', 'Quatiguá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120804', 'Quatro Barras', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120853', 'Quatro Pontes', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4120903', 'Quedas do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121000', 'Querência do Norte', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121109', 'Quinta do Sol', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121208', 'Quitandinha', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121257', 'Ramilândia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121307', 'Rancho Alegre', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121356', 'Rancho Alegre D''Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121406', 'Realeza', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121505', 'Rebouças', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121604', 'Renascença', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121703', 'Reserva', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121752', 'Reserva do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121802', 'Ribeirão Claro', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4121901', 'Ribeirão do Pinhal', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122008', 'Rio Azul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122107', 'Rio Bom', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122156', 'Rio Bonito do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122172', 'Rio Branco do Ivaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122206', 'Rio Branco do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122305', 'Rio Negro', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122404', 'Rolândia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122503', 'Roncador', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122602', 'Rondon', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122651', 'Rosário do Ivaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122701', 'Sabáudia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122800', 'Salgado Filho', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4122909', 'Salto do Itararé', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123006', 'Salto do Lontra', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123105', 'Santa Amélia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123204', 'Santa Cecília do Pavão', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123303', 'Santa Cruz de Monte Castelo', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123402', 'Santa Fé', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123501', 'Santa Helena', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123600', 'Santa Inês', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123709', 'Santa Isabel do Ivaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123808', 'Santa Izabel do Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123824', 'Santa Lúcia', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123857', 'Santa Maria do Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123907', 'Santa Mariana', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4123956', 'Santa Mônica', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124004', 'Santana do Itararé', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124020', 'Santa Tereza do Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124053', 'Santa Terezinha de Itaipu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124103', 'Santo Antônio da Platina', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124202', 'Santo Antônio do Caiuá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124301', 'Santo Antônio do Paraíso', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124400', 'Santo Antônio do Sudoeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124509', 'Santo Inácio', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124608', 'São Carlos do Ivaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124707', 'São Jerônimo da Serra', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124806', 'São João', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4124905', 'São João do Caiuá', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125001', 'São João do Ivaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125100', 'São João do Triunfo', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125209', 'São Jorge D''Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125308', 'São Jorge do Ivaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125357', 'São Jorge do Patrocínio', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125407', 'São José da Boa Vista', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125456', 'São José das Palmeiras', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125506', 'São José dos Pinhais', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125555', 'São Manoel do Paraná', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125605', 'São Mateus do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125704', 'São Miguel do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125753', 'São Pedro do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125803', 'São Pedro do Ivaí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4125902', 'São Pedro do Paraná', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126009', 'São Sebastião da Amoreira', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126108', 'São Tomé', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126207', 'Sapopema', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126256', 'Sarandi', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126272', 'Saudade do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126306', 'Sengés', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126355', 'Serranópolis do Iguaçu', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126405', 'Sertaneja', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126504', 'Sertanópolis', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126603', 'Siqueira Campos', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126652', 'Sulina', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126678', 'Tamarana', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126702', 'Tamboara', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126801', 'Tapejara', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4126900', 'Tapira', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127007', 'Teixeira Soares', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127106', 'Telêmaco Borba', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127205', 'Terra Boa', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127304', 'Terra Rica', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127403', 'Terra Roxa', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127502', 'Tibagi', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127601', 'Tijucas do Sul', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127700', 'Toledo', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127809', 'Tomazina', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127858', 'Três Barras do Paraná', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127882', 'Tunas do Paraná', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127908', 'Tuneiras do Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127957', 'Tupãssi', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4127965', 'Turvo', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128005', 'Ubiratã', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128104', 'Umuarama', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128203', 'União da Vitória', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128302', 'Uniflor', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128401', 'Uraí', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128500', 'Wenceslau Braz', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128534', 'Ventania', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128559', 'Vera Cruz do Oeste', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128609', 'Verê', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128625', 'Alto Paraíso', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128633', 'Doutor Ulysses', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128658', 'Virmond', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128708', 'Vitorino', 16, NULL, NULL);
INSERT INTO MUNICIPIO (CODIGO_IBGE, NOME, ID_UF, CODIGO_RECEITA_FEDERAL, CODIGO_ESTADUAL)
values ('4128807', 'Xambrê', 16, NULL, NULL);